[package]
name = "rust"
version = "0.1.0"
authors = ["Jakub Darul <jakub.darul@codeheroes.io>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
reqwest = "0.9.14"
serde = "0.5.0"
serde-pickle = "0.5.0"
regex = "1"